# Generated by Django 5.0.6 on 2024-08-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
