# Generated by Django 5.0.6 on 2024-08-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_alter_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_book',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
