# Generated by Django 5.0.6 on 2024-08-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_borrow_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
