# Generated by Django 5.0.6 on 2024-08-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_alter_borrow_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Rating',
            field=models.CharField(blank=True, choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=40, null=True),
        ),
    ]
